services:
  samowarium:
    build: .
    image: vzalygin/samowarium:${DOCKER_TAG:-latest}
    working_dir: /samowarium
    env_file:
      - .env
    volumes:
      - db:/samowarium/db:rw
      - logs:/samowarium/logs:rw
    entrypoint:
      - python3
    command:
      - samowarium.py
    restart: unless-stopped
    ports:
      - "53000:53000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:12.22
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    restart: unless-stopped
    ports:
      - "6433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  db:
  logs:
  postgres-data:
