# timeouts
HTTP_COMMON_TIMEOUT_SEC = 5
HTTP_FILE_LOAD_TIMEOUT_SEC = 30
HTTP_CONNECT_LONGPOLL_TIMEOUT_SEC = 60
HTTP_TOTAL_LONGPOLL_TIMEOUT_SEC = 80
HTTP_RETRY_DELAY_SEC = 10
TELEGRAM_SEND_RETRY_DELAY_SEC = 2

# tg message formats
MARKDOWN_FORMAT = "Markdown"
MARKDOWN_FORMAT_V2 = "MarkdownV2"

# logs
LOGGER_FOLDER_PATH = "logs"
LOGGER_PATH = f"{LOGGER_FOLDER_PATH}/samowarium.log"
