name: Build and push job

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-and-push-image:
    name: Build and push image tag ${{ inputs.tag }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Login to Docker Hub
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Cache image
    #   uses: satackey/action-docker-layer-caching@v0.0.11
    #   continue-on-error: true

    - name: Build and push image
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.tag }}
