name: Deploy to production stand

concurrency: deploy-prod

on:
  workflow_dispatch:
    inputs:
      production-check:
        description: 'DEPLOY TO PRODUCTION'
        type: boolean
        default: false
        required: true

jobs:
  build-and-push:
    if: ${{ inputs.production-check }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      tag: latest

  deploy:
    needs: build-and-push
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      tag: latest
      environment: prod
