name: Deploy to development stand

concurrency: deploy-dev

on:
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      tag: dev

  deploy:
    needs: build-and-push
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      tag: dev
      environment: dev
